services:
  jekyll:
    container_name: "apidocs-jekyll"
    restart: unless-stopped
    # image: apivpc/apidocs-jekyll:latest
    build:
      context: ./container/jekyll/.
      dockerfile: Dockerfile
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - jekyll-bundle:/usr/local/bundle
      - ./:/site
    ### Install: provide at least a blank Jekyll Gemfile
    # command: "bundle install"
    ### Serve: Enable after Installation
    # command: "bundle exec jekyll serve --verbose --trace --incremental --livereload --livereload-port 35729 --host 0.0.0.0 --port 4000"
    command: "bundle exec jekyll serve --incremental --host 0.0.0.0 --port 4000 --livereload --livereload-port 35729"

volumes:
  jekyll-bundle:
